name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./AppConsole/AppConsole.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ./AppConsole/AppConsole.csproj
    - name: Build test
      run: dotnet build ./AppConsole.Tests/AppConsole.Tests.csproj
    - name: Test
      run: dotnet test ./AppConsole.Tests/ --no-restore -v m /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./coverage/lcov.info'
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
